name: DisableInteraction
version: 1.0.0
main: me.TheNorthFeng.DisableInteraction.Main
api-version: 1.15
authors: [ TheNorthFeng ]
description: 禁止玩家与任何事物互动
commands:
  DisableInteraction:
    description: 插件主指令
    usage: /DisableInteraction <子命令>
    aliases: di
